/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package computer.sales.system;

import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NAvi N Du
 */
public class InvoicePrint extends javax.swing.JFrame {

    DefaultTableModel ip_table;
    ResultSet res = null;
    int qcount;
    
    /**
     * Creates new form InvoicePrint
     */
    public InvoicePrint() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        this.setTitle("Bill");
        getDate();
        setCompanyInfo();
    }
    
    public InvoicePrint(String cash, String bal, String tot, String cust, String invoId, String cashier, String discA) {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        this.setTitle("Bill");
        getDate();
        ip_Cash.setText("Rs." + cash + ".00");
        ip_Bal.setText("Rs." + bal);
        ip_Tot.setText("Rs." + tot);
        ip_Cust.setText(cust);
        ip_InID.setText(invoId);
        ip_Cashier.setText(cashier);
        ip_Disc.setText("Rs." + discA);
        addToIPTableRows();
        setCompanyInfo();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ip_panel = new javax.swing.JPanel();
        ip_address = new javax.swing.JLabel();
        ip_Companyname = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ip_InID = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ip_Date = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ip_Bal = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ip_Tot = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ip_Cash = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ip_contact = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ip_Table = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        ip_Cust = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ip_Disc = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ip_Cashier = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ip_panel.setBackground(new java.awt.Color(255, 255, 255));
        ip_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ip_address.setFont(new java.awt.Font("Bahnschrift", 1, 10)); // NOI18N
        ip_address.setForeground(new java.awt.Color(0, 0, 0));
        ip_address.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ip_address.setText("<address>");
        ip_panel.add(ip_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 340, 10));

        ip_Companyname.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        ip_Companyname.setForeground(new java.awt.Color(0, 0, 0));
        ip_Companyname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ip_Companyname.setText("<company name>");
        ip_Companyname.setAutoscrolls(true);
        ip_panel.add(ip_Companyname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 60));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("================================================");
        ip_panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 340, 20));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Invoice ID : ");
        ip_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        ip_InID.setForeground(new java.awt.Color(0, 0, 0));
        ip_InID.setText("<invoice id>");
        ip_panel.add(ip_InID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 80, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Date : ");
        ip_panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        ip_Date.setForeground(new java.awt.Color(0, 0, 0));
        ip_Date.setText("<date/time>");
        ip_panel.add(ip_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 120, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Item name");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Price");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Qty");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)))
        );

        ip_panel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 340, 30));

        ip_Bal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ip_Bal.setForeground(new java.awt.Color(0, 0, 0));
        ip_Bal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ip_Bal.setText("0.00");
        ip_panel.add(ip_Bal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 100, 30));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Balance");
        ip_panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 60, 30));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Total");
        ip_panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 60, 30));

        ip_Tot.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ip_Tot.setForeground(new java.awt.Color(0, 0, 0));
        ip_Tot.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ip_Tot.setText("0.00");
        ip_panel.add(ip_Tot, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 100, 30));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Cash");
        ip_panel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 60, 30));

        ip_Cash.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ip_Cash.setForeground(new java.awt.Color(0, 0, 0));
        ip_Cash.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ip_Cash.setText("0.00");
        ip_panel.add(ip_Cash, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 90, 30));

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("================================================");
        ip_panel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 340, 30));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("THANK YOU!  COME AGAIN.");
        ip_panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 340, -1));

        ip_contact.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        ip_contact.setForeground(new java.awt.Color(0, 0, 0));
        ip_contact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ip_contact.setText("<Contact No>");
        ip_panel.add(ip_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 340, 10));

        ip_Table.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ip_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item name", "Qty", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ip_Table);
        if (ip_Table.getColumnModel().getColumnCount() > 0) {
            ip_Table.getColumnModel().getColumn(0).setMaxWidth(500);
            ip_Table.getColumnModel().getColumn(1).setMaxWidth(50);
            ip_Table.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        ip_panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 340, 240));

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Customer : ");
        ip_panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, -1));

        ip_Cust.setForeground(new java.awt.Color(0, 0, 0));
        ip_Cust.setText("<ip_cust>");
        ip_panel.add(ip_Cust, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 260, -1));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Disc. Amount");
        ip_panel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 60, 30));

        ip_Disc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ip_Disc.setForeground(new java.awt.Color(0, 0, 0));
        ip_Disc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ip_Disc.setText("0.00");
        ip_panel.add(ip_Disc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 90, 30));

        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Cashier");
        ip_panel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, -1));

        ip_Cashier.setForeground(new java.awt.Color(0, 0, 0));
        ip_Cashier.setText("<ip_cashier>");
        ip_panel.add(ip_Cashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 260, -1));

        getContentPane().add(ip_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 500));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 502, 80, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Invoice print Print button
        
        printRecord(ip_panel);
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
//################################################################### my functions ##################################################################
    /**
     * @param args the command line arguments
     */
    public void getDate() {
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat sdf1 = new SimpleDateFormat("HH:mm:ss");
        
        ip_Date.setText(sdf.format(date) + " " + sdf1.format(date));
    }
    
    public void addToIPTableRows(){
        
        String in_ID = ip_InID.getText();
        
        try {
            DataOb.dbConnects();
            System.out.println("Database connected " + in_ID);
            
            res = DataOb.viewSelected("invoiceprinttable", "Invoice_ID", in_ID);
            ResultSetMetaData stData = res.getMetaData();
            
            qcount = stData.getColumnCount();
            
            DefaultTableModel ip_table = (DefaultTableModel) ip_Table.getModel();
            ip_table.setRowCount(0);
            
            while(res.next()){
                Vector columnData = new Vector();
                
                for(int i = 1; i <= qcount; i++){
                    
                    columnData.add(res.getString("In_Item"));
                    columnData.add(res.getString("In_Qty"));
                    
                    double qty = Double.parseDouble(res.getString("In_Qty"));
                    double price = Double.parseDouble(res.getString("IsellingPrice"));
                    System.out.println(qty + " * " + price);
                    
                    price = price * qty;
                    System.out.println(price);
                    
                    columnData.add(price);
                }
                ip_table.addRow(columnData);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }
    
    public void setCompanyInfo(){
        
        try {
            DataOb.dbConnects();
            res = DataOb.viewSelected("company_info", "No", "1");

            if (res.next()) {
                ip_Companyname.setText(res.getString("Campany_Name"));
                ip_address.setText(res.getString("Address_1") + res.getString("City") + ", " + res.getString("Province"));
                ip_contact.setText(res.getString("Company_Contact"));
            }
            
        } catch (Exception ex) {
            System.out.println("err!");
        }
    }
    
//################################################################## my functions #####################################################################
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoicePrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoicePrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoicePrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoicePrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoicePrint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ip_Bal;
    private javax.swing.JLabel ip_Cash;
    private javax.swing.JLabel ip_Cashier;
    private javax.swing.JLabel ip_Companyname;
    private javax.swing.JLabel ip_Cust;
    private javax.swing.JLabel ip_Date;
    private javax.swing.JLabel ip_Disc;
    private javax.swing.JLabel ip_InID;
    private javax.swing.JTable ip_Table;
    private javax.swing.JLabel ip_Tot;
    private javax.swing.JLabel ip_address;
    private javax.swing.JLabel ip_contact;
    private javax.swing.JPanel ip_panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    //####################################################################my functions##############################################################
    
    private void printRecord(JPanel panel) {

        PrinterJob printerJob = PrinterJob.getPrinterJob();

        printerJob.setJobName("Print Record");

        printerJob.setPrintable(new Printable() {
            @Override
            public int print(java.awt.Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                if (pageIndex > 0) {
                    return Printable.NO_SUCH_PAGE;
                }

                Graphics2D graphics2D = (Graphics2D) graphics;
                graphics2D.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
                graphics2D.scale(0.8, 1.0);

                panel.paint(graphics2D);

                return Printable.PAGE_EXISTS;
            }
        });

        boolean returningResult = printerJob.printDialog();

        if (returningResult) {
            try {
                printerJob.print();
            } catch (PrinterException printerException) {
                JOptionPane.showMessageDialog(this, "Prinr Error: " + printerException.getMessage());
            }
        }
    }

}
