/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package computer.sales.system;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author NAvi N Du
 */
public class Login extends javax.swing.JFrame {

    String msg;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userchk = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblclear = new javax.swing.JLabel();
        lblclear1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("L O G I N . . .");
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setAutoscrolls(true);

        jLabel2.setForeground(new java.awt.Color(255, 153, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("User Name");
        jLabel2.setAlignmentY(0.0F);
        jLabel2.setAutoscrolls(true);

        user.setForeground(new java.awt.Color(255, 153, 102));
        user.setAlignmentX(0.0F);
        user.setAlignmentY(0.0F);
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userKeyReleased(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 153, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Password");
        jLabel3.setAlignmentY(0.0F);
        jLabel3.setAutoscrolls(true);

        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passKeyReleased(evt);
            }
        });

        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CSS/img/Untitled-1.png"))); // NOI18N
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CSS/img/delete.png"))); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        lbl1.setForeground(new java.awt.Color(255, 51, 51));
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("WELCOME");

        lblclear.setForeground(new java.awt.Color(51, 51, 51));
        lblclear.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblclear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblclearMouseClicked(evt);
            }
        });

        lblclear1.setForeground(new java.awt.Color(51, 51, 51));
        lblclear1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblclear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblclear1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancel)
                                .addGap(18, 18, 18)
                                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblclear, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addComponent(lblclear1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblclear, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblclear1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String uname = "";

    public String uname() {
        System.out.println(uname);
        return uname;
    }

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed

        lblclear.setText("");
        lblclear1.setText("");

        String a = user.getText();
        String b = pass.getText();

        //rename frontend cashier name test 1 :(
//        FrontEnd fe = new FrontEnd();
//        fe.cName.setText(Login.user.getText());
        if (a.equals("") || b.equals("")) {
            lbl1.setText("User name or password should be filled");
            user.requestFocus();
            
        /*} else if (a.equals("admin")) {
            if (b.equals("0000")) {
                dispose();
                this.uname = a;
                System.out.println(uname);
                msg = user.getText();
                new Inventory().setVisible(true);
            } else {
                lbl1.setText("User name or password is incorrect!");
                user.setText("");
                pass.setText("");
                user.requestFocus();
            }
        } else if (a.equals("user")) {
            if (b.equals("1111")) {
                dispose();
                this.uname = a;
                System.out.println(uname);
                msg = user.getText();
                new FrontEnd(msg).setVisible(true);///////
                FrontEnd.cName.setText(Login.user.getText());
            } else {
                lbl1.setText("User name or password is incorrect!");
                user.setText("");
                pass.setText("");
                user.requestFocus();
            }
        */} else {
            try {
                DataOb.dbConnects();
                System.out.println("Database connection success");

                ResultSet rs = DataOb.andView2columns("users", "UName", a, "UPassword", b);

                if (rs.next()) {
                    this.uname = a;
                    System.out.println(uname);

                    String post = rs.getString("Post");
                    System.out.println(post);

                    if (post.equals("Admin")) {
                        dispose();

                        new Inventory().setVisible(true);
                    } else if (post.equals("Cashier")) {
                        dispose();
                        msg = user.getText();
                        new FrontEnd(msg).setVisible(true);

                    } else {
                        lbl1.setText("User's 'POST' is Incorrect! Call 119 :-(");
                        user.setText("");
                        pass.setText("");
                        user.requestFocus();
                    }

                } else if (!(rs.next())) {
                    lbl1.setText("User name or password is incorrect!");
                    user.setText("");
                    pass.setText("");
                    user.requestFocus();
                }

            } catch (Exception ex) {
                System.out.println(ex);
                lbl1.setText("User name or password is incorrect!");
                user.setText("");
                pass.setText("");
                user.requestFocus();
            }
        }
    }//GEN-LAST:event_loginActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cancelActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyPressed

        
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String a = user.getText();
            String b = pass.getText();

            lblclear.setText("");
            lblclear1.setText("");
            //rename frontend cashier name test 1 :(
//        FrontEnd fe = new FrontEnd();
//        fe.cName.setText(Login.user.getText());
            if (a.equals("") || b.equals("")) {
                lbl1.setText("User name or password should be filled");
                user.requestFocus();
            } else if (a.equals("admin")) {
                if (b.equals("0000")) {
                    dispose();
                    this.uname = a;
                    System.out.println(uname);
                    msg = user.getText();
                    new Inventory().setVisible(true);
                } else {
                    lbl1.setText("User name or password is incorrect!");
                    user.setText("");
                    pass.setText("");
                    user.requestFocus();
                }
            } else if (a.equals("user")) {
                if (b.equals("1111")) {
                    dispose();
                    this.uname = a;
                    System.out.println(uname);
                    msg = user.getText();
                    new FrontEnd(msg).setVisible(true);
                    FrontEnd.cName.setText(Login.user.getText());
                } else {
                    lbl1.setText("User name or password is incorrect!");
                    user.setText("");
                    pass.setText("");
                    user.requestFocus();
                }
            } else {
                try {
                    DataOb.dbConnects();
                    System.out.println("Database connection success");

                    ResultSet rs = DataOb.andView2columns("users", "UName", a, "UPassword", b);

                    if (rs.next()) {
                        this.uname = a;
                        System.out.println(uname);

                        String post = rs.getString("Post");
                        System.out.println(post);

                        if (post.equals("Admin")) {
                            dispose();

                            new Inventory().setVisible(true);
                        } else if (post.equals("Cashier")) {
                            dispose();
                            msg = user.getText();
                            new FrontEnd(msg).setVisible(true);

                        } else {
                            lbl1.setText("User's 'POST' is Incorrect! Call 119 :-(");
                            user.setText("");
                            pass.setText("");
                            user.requestFocus();
                        }

                    } else if (!(rs.next())) {
                        lbl1.setText("User name or password is incorrect!");
                        user.setText("");
                        pass.setText("");
                        user.requestFocus();
                    }

                } catch (Exception ex) {
                    System.out.println(ex);
                    lbl1.setText("User name or password is incorrect!");
                    user.setText("");
                    pass.setText("");
                    user.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_passKeyPressed

    private void userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            pass.requestFocus();
        }

    }//GEN-LAST:event_userKeyPressed

    private void userKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userKeyReleased

        if (user.getText().equals("")) {
            lblclear.setText("");
        } else {
            lblclear.setText("Clear");
        }

    }//GEN-LAST:event_userKeyReleased

    private void lblclearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblclearMouseClicked
        user.setText("");
        lblclear.setText("");
        user.requestFocus();
    }//GEN-LAST:event_lblclearMouseClicked

    private void lblclear1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblclear1MouseClicked
        if (user.getText().equals("")) {
            pass.setText("");
            lblclear1.setText("");
            user.requestFocus();
        } else {
            pass.setText("");
            lblclear1.setText("");
            pass.requestFocus();
        }

    }//GEN-LAST:event_lblclear1MouseClicked

    private void passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyReleased

        if (pass.getText().equals("")) {
            lblclear1.setText("");
        } else {
            lblclear1.setText("Clear");
        }
    }//GEN-LAST:event_passKeyReleased

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lblclear;
    private javax.swing.JLabel lblclear1;
    private javax.swing.JButton login;
    public static javax.swing.JPasswordField pass;
    public static javax.swing.JTextField user;
    private javax.swing.ButtonGroup userchk;
    // End of variables declaration//GEN-END:variables
}
